kind: ConfigMap 
apiVersion: v1 
metadata:
  name: {{ .Values.configmap.name }}
  namespace: {{ .Values.namespace }}
data:
  CLIENT_PORT: {{ .Values.configmap.data.CLIENT_PORT }}
  MATH_API_ENDPOINT: {{ .Values.configmap.data.MATH_API_ENDPOINT }}