apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appName }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.appName }}
spec:
  ports:
  - port: {{ .Values.port }}
    protocol: TCP
    name: "api-{{ .Values.appName }}"
  selector:
    app: {{ .Values.appName }}
    tier: backend
  type: LoadBalancer
  externalIPs:
  - 192.168.123.211